# Use a special RP
resource_pack: "https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FNightScythe1%2FMagic-Supernaturals-RP%2Ftree%2Fmain%2Fresource_pack"

# Use a different RP when combined with other configs
# add_resource_pack: "http://<somewhere else or maybe same place? not sure eventually this would be a combined one>.zip"

# Alternate resource packs can be accessed with /getrp <pack>
alternate_resource_packs:
  supernaturals:
    url: "https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FNightScythe1%2FMagic-Supernaturals-RP%2Ftree%2Fmain%2Fresource_pack"